## Fixations numerations fix

+ Change the numeration of trials once they are separated in Like and Dislike conditions (avoid breaks in trial number)
+ Calculate the gaze time for each trial

In [1]:
import numpy as np
import pandas as pd
from pandas.core.frame import DataFrame as DF
import seaborn as sns
sns.set(color_codes=True)
#np.random.seed(sum(map(ord, "distributions")))
from sklearn import linear_model  # packages for the logistic regression function to plot the logistic regression 
from sklearn.linear_model import LogisticRegression # packages for the logistic regression function to plot the logistic regression 
import scipy
from scipy import stats, integrate
from scipy.stats import mode
from scipy.stats.stats import pearsonr # Pearson's correlation
from copy import copy as copy
import operator as operator
import pylab

# MORE condition data

In [2]:
#for not binned data
data_fix = pd.read_csv('/Users/pradyumna/Documents/GiTs/PF2019/Output/fixations_collapsed_PF2019_More_33.csv') 
data_expData = pd.read_csv('/Users/pradyumna/Documents/GiTs/PF2019/Output/expdata_PF2019_More_33.csv') 

data_expData = data_expData.apply(pd.to_numeric, errors='ignore')
data_fix = data_fix.apply(pd.to_numeric, errors='ignore')

In [3]:
data_fix

       parcode  trial  fix_item  fix_time
0            1     80         0   171.000
1            1     80         1   868.000
2            1     80         0   266.000
3            1     80         2   429.284
4            1     81         0   235.000
5            1     81         1   314.000
6            1     81         2   680.000
7            1     81         1   696.000
8            1     81         2   770.000
9            1     81         1  1490.000
10           1     81         0   288.000
11           1     81         1  2082.370
12           1     82         0   161.000
13           1     82         1   696.000
14           1     82         2   632.000
15           1     82         1   704.000
16           1     82         2   726.000
17           1     82         1   255.566
18           1     83         0   136.000
19           1     83         1   832.000
20           1     83         2   620.000
21           1     83         1   836.000
22           1     83         2   453.579
23           1     84         0   150.000
24           1     84         1   866.000
25           1     84         2   790.310
26           1     85         0    67.000
27           1     85         1   574.000
28           1     85         0   376.000
29           1     85         2   638.000
...        ...    ...       ...       ...
23021       33    234         2   732.000
23022       33    234         1   762.000
23023       33    234         2   844.448
23024       33    235         0   225.000
23025       33    235         1   494.000
23026       33    235         2   798.000
23027       33    235         1  1056.000
23028       33    235         2   928.000
23029       33    235         1   526.628
23030       33    236         3     0.000
23031       33    236         1  1933.000
23032       33    236         2   905.649
23033       33    237         0   172.000
23034       33    237         1   854.000
23035       33    237         2  1322.000
23036       33    237         1  1462.000
23037       33    237         2  1736.000
23038       33    237         1  1282.000
23039       33    237         2   664.000
23040       33    237         1   716.000
23041       33    237         0    70.587
23042       33    238         3     0.000
23043       33    238         1   429.000
23044       33    238         2  1258.000
23045       33    238         1  1104.000
23046       33    238         2  1115.836
23047       33    239         3     0.000
23048       33    239         1   400.000
23049       33    239         2  1082.000
23050       33    239         1  1100.740

[23051 rows x 4 columns]

In [4]:
print(data_fix.parcode.unique())
print(data_expData.parcode.unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]

## Replace numerations

In [5]:
partNums = pd.unique(data_fix["parcode"])

new_fix_dataframe = data_fix.iloc[0:0]
new_expData_dataframe = data_expData.iloc[0:0]

for i in partNums:
    old_index_trial = []
    new_index_trial = []
    participant_trials = []
    
    participant_trials = data_expData.loc[data_expData['parcode'] == i]
    part_fix_trials = data_fix.loc[data_fix['parcode'] == i]
    
    old_index_trial = participant_trials['trial'].values
    new_index_trial = range(len(old_index_trial))
    
    for j in new_index_trial:
            #insert new column with new trial numeration : case trialData
            trialCol2Replace = participant_trials['trial'].replace(old_index_trial[j], new_index_trial[j])
            participant_trials = participant_trials.drop(['trial'], axis=1)
            participant_trials.insert(1,'trial',trialCol2Replace)
            
            #insert new column with new trial numeration : case Fixations
            fixCol2Replace = part_fix_trials['trial'].replace(old_index_trial[j], new_index_trial[j]).values
            part_fix_trials = part_fix_trials.drop(['trial'], axis=1)
            part_fix_trials.insert(1,'trial',fixCol2Replace)
            
            #print (participant_trials)
            time_trials = part_fix_trials['fix_time'].values
            
            ix = np.in1d(time_trials, 0)
            delete_fix_idx = np.where(ix)
            part_fix_trials = part_fix_trials.drop(part_fix_trials.index[delete_fix_idx])
            
    new_fix_dataframe = pd.concat([new_fix_dataframe, part_fix_trials],axis = 0)
    new_expData_dataframe = pd.concat([new_expData_dataframe, participant_trials], axis = 0)

## Format appropiate for GLAM toolbox for fixations
Agregate fixations for each IA (similar to dwelling time)

In [6]:
new_fix_dataframe.parcode.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [7]:
new_fix_dataframe

       parcode  trial  fix_item  fix_time
0            1     80         0   171.000
1            1     80         1   868.000
2            1     80         0   266.000
3            1     80         2   429.284
4            1     81         0   235.000
5            1     81         1   314.000
6            1     81         2   680.000
7            1     81         1   696.000
8            1     81         2   770.000
9            1     81         1  1490.000
10           1     81         0   288.000
11           1     81         1  2082.370
12           1     82         0   161.000
13           1     82         1   696.000
14           1     82         2   632.000
15           1     82         1   704.000
16           1     82         2   726.000
17           1     82         1   255.566
18           1     83         0   136.000
19           1     83         1   832.000
20           1     83         2   620.000
21           1     83         1   836.000
22           1     83         2   453.579
23           1     84         0   150.000
24           1     84         1   866.000
25           1     84         2   790.310
26           1     85         0    67.000
27           1     85         1   574.000
28           1     85         0   376.000
29           1     85         2   638.000
...        ...    ...       ...       ...
23017       33    233         1   688.000
23018       33    233         2   350.699
23020       33    234         1   513.000
23021       33    234         2   732.000
23022       33    234         1   762.000
23023       33    234         2   844.448
23024       33    235         0   225.000
23025       33    235         1   494.000
23026       33    235         2   798.000
23027       33    235         1  1056.000
23028       33    235         2   928.000
23029       33    235         1   526.628
23031       33    236         1  1933.000
23032       33    236         2   905.649
23033       33    237         0   172.000
23034       33    237         1   854.000
23035       33    237         2  1322.000
23036       33    237         1  1462.000
23037       33    237         2  1736.000
23038       33    237         1  1282.000
23039       33    237         2   664.000
23040       33    237         1   716.000
23041       33    237         0    70.587
23043       33    238         1   429.000
23044       33    238         2  1258.000
23045       33    238         1  1104.000
23046       33    238         2  1115.836
23048       33    239         1   400.000
23049       33    239         2  1082.000
23050       33    239         1  1100.740

[22549 rows x 4 columns]

In [8]:
partNums = pd.unique(new_fix_dataframe["parcode"])
partNums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [9]:
new_fix_dataframe

       parcode  trial  fix_item  fix_time
0            1     80         0   171.000
1            1     80         1   868.000
2            1     80         0   266.000
3            1     80         2   429.284
4            1     81         0   235.000
5            1     81         1   314.000
6            1     81         2   680.000
7            1     81         1   696.000
8            1     81         2   770.000
9            1     81         1  1490.000
10           1     81         0   288.000
11           1     81         1  2082.370
12           1     82         0   161.000
13           1     82         1   696.000
14           1     82         2   632.000
15           1     82         1   704.000
16           1     82         2   726.000
17           1     82         1   255.566
18           1     83         0   136.000
19           1     83         1   832.000
20           1     83         2   620.000
21           1     83         1   836.000
22           1     83         2   453.579
23           1     84         0   150.000
24           1     84         1   866.000
25           1     84         2   790.310
26           1     85         0    67.000
27           1     85         1   574.000
28           1     85         0   376.000
29           1     85         2   638.000
...        ...    ...       ...       ...
23017       33    233         1   688.000
23018       33    233         2   350.699
23020       33    234         1   513.000
23021       33    234         2   732.000
23022       33    234         1   762.000
23023       33    234         2   844.448
23024       33    235         0   225.000
23025       33    235         1   494.000
23026       33    235         2   798.000
23027       33    235         1  1056.000
23028       33    235         2   928.000
23029       33    235         1   526.628
23031       33    236         1  1933.000
23032       33    236         2   905.649
23033       33    237         0   172.000
23034       33    237         1   854.000
23035       33    237         2  1322.000
23036       33    237         1  1462.000
23037       33    237         2  1736.000
23038       33    237         1  1282.000
23039       33    237         2   664.000
23040       33    237         1   716.000
23041       33    237         0    70.587
23043       33    238         1   429.000
23044       33    238         2  1258.000
23045       33    238         1  1104.000
23046       33    238         2  1115.836
23048       33    239         1   400.000
23049       33    239         2  1082.000
23050       33    239         1  1100.740

[22549 rows x 4 columns]

## Check that all particpants have enough trials

In [10]:
for i in partNums:
    PartIAFixMatrix= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == i )]
    print(str(i) +" : " + str(len(PartIAFixMatrix.trial.unique())))

1 : 120
2 : 120
3 : 120
4 : 120
5 : 120
6 : 120
7 : 120
8 : 120
9 : 120
10 : 120
11 : 120
12 : 120
13 : 120
14 : 120
15 : 120
16 : 120
17 : 120
18 : 120
19 : 120
20 : 120
21 : 120
22 : 120
23 : 120
24 : 120
25 : 120
26 : 120
27 : 120
28 : 120
29 : 120
30 : 120
31 : 120
32 : 120
33 : 120

In [11]:
IAFixMatrix = []

for i in partNums:
    PartIAFixMatrix= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == i )]
    trialNums = pd.unique(PartIAFixMatrix["trial"])
    for j in trialNums:
        PartTrialIAFixMatrix= PartIAFixMatrix.loc[(PartIAFixMatrix['trial'] == j )]
        # considering that IA 1 is left and IA 2 is right ( IAs 3 and 0 are not fixated in the item)
        # Sum left item
        LGazeTime = PartTrialIAFixMatrix.loc[PartTrialIAFixMatrix['fix_item'] == 1, 'fix_time'].sum() 
        # Sum right item
        RGazeTime = PartTrialIAFixMatrix.loc[PartTrialIAFixMatrix['fix_item'] == 2, 'fix_time'].sum()  
        LGaze = LGazeTime/(LGazeTime + RGazeTime)
        RGaze = RGazeTime/(LGazeTime + RGazeTime)
        
        RT = PartTrialIAFixMatrix.fix_time.sum()
        
        #IAFixMatrix.append([i,j,LGaze, RGaze]) 
        IAFixMatrix.append([LGaze, RGaze,RT]) 
        
        if abs(LGaze)> 1:
            print (LGazeTime)
            print (RGazeTime)
            print ('part' + str(i) +'trial' + str(j))
        
        IAFixMatrix.append([LGaze, RGaze])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in double_scalars

In [12]:
IAFixDataFrame = pd.DataFrame(IAFixMatrix,columns=['gaze_0','gaze_1'])

In [13]:
len(IAFixDataFrame)

3960

In [14]:
IAFixDataFrame

        gaze_0    gaze_1
0     0.669090  0.330910
1     0.759630  0.240370
2     0.549371  0.450629
3     0.608409  0.391591
4     0.522849  0.477151
5     0.559774  0.440226
6     0.682034  0.317966
7     0.565221  0.434779
8     0.508019  0.491981
9     0.558373  0.441627
10    0.582089  0.417911
11    0.628642  0.371358
12    0.666353  0.333647
13    0.699508  0.300492
14    0.508035  0.491965
15    0.746166  0.253834
16    0.473512  0.526488
17    0.508536  0.491464
18    0.553242  0.446758
19    0.623107  0.376893
20    0.575306  0.424694
21    0.658431  0.341569
22    0.435523  0.564477
23    0.565623  0.434377
24    0.528335  0.471665
25    0.555439  0.444561
26    0.485035  0.514965
27    0.550045  0.449955
28    0.698379  0.301621
29    0.577821  0.422179
...        ...       ...
3930  0.477459  0.522541
3931  0.496641  0.503359
3932  0.484599  0.515401
3933  0.622399  0.377601
3934  0.529970  0.470030
3935  0.541535  0.458465
3936  0.539153  0.460847
3937  0.452997  0.547003
3938  0.513330  0.486670
3939  0.446438  0.553562
3940  0.557839  0.442161
3941  0.440358  0.559642
3942  0.582175  0.417825
3943  0.569912  0.430088
3944  0.399461  0.600539
3945  0.491064  0.508936
3946  0.492486  0.507514
3947  0.508692  0.491308
3948  0.593629  0.406371
3949  0.559559  0.440441
3950  0.476386  0.523614
3951  0.596979  0.403021
3952  0.584644  0.415356
3953  0.518223  0.481777
3954  0.447141  0.552859
3955  0.546103  0.453897
3956  0.680958  0.319042
3957  0.536834  0.463166
3958  0.392389  0.607611
3959  0.581065  0.418935

[3960 rows x 2 columns]

In [15]:
data_expData

      parcode  trial         rt  choice  item_left  item_right
0           1     40   1734.284       1        110         131
1           1     41   6555.370      -1         47          50
2           1     42   3174.566      -1         50          44
3           1     43   2877.579       1         57          50
4           1     44   1806.310       1         42          50
5           1     45   3636.816      -1        108         110
6           1     46   3650.266       1         78          80
7           1     47   3078.223      -1        110          92
8           1     48   1259.268       1         50          48
9           1     49   3440.738      -1        110         101
10          1     50   5698.027       1         46          50
11          1     51   8224.467       1         80          83
12          1     52   2626.168       1         50          56
13          1     53   1991.413      -1         50          47
14          1     54   1671.149       1        110         124
15          1     55   2607.607      -1         91          80
16          1     56   1527.826       1         64          80
17          1     57   5043.160      -1         83          80
18          1     58   2267.665       1        101         110
19          1     59   4499.543      -1         56          50
20          1     60   5571.061      -1         50          42
21          1     61   2045.641       1        110         117
22          1     62   1402.112       1         77          80
23          1     63   2736.625       1         80          91
24          1     64   2065.604       1         44          50
25          1     65   3058.203       1         50          57
26          1     66   1613.454       1         50          46
27          1     67   1931.482       1        110         108
28          1     68   4895.517      -1        133         110
29          1     69   3197.860       1        131         110
...       ...    ...        ...     ...        ...         ...
3930       33    170   3936.449      -1         80          70
3931       33    171   2977.221      -1         80          93
3932       33    172  11964.377      -1         82          80
3933       33    173   4135.630      -1         50          41
3934       33    174   2743.440       1         96         110
3935       33    175   3397.340      -1         80          85
3936       33    176   2532.466      -1         60          50
3937       33    177   6140.558      -1         41          50
3938       33    178   6412.806       1        110          96
3939       33    179   4655.703       1         72          80
3940       33    180   4007.788      -1         49          50
3941       33    181   5057.656      -1         43          50
3942       33    182   3685.316      -1         51          50
3943       33    183   5533.621       1        112         110
3944       33    184   1988.182       1         40          50
3945       33    185   5891.906       1         50          51
3946       33    186   4300.777      -1         85          80
3947       33    187   5242.890      -1         50          49
3948       33    188   7640.657      -1         50          43
3949       33    189   3754.229      -1         80          82
3950       33    190   3341.929       1         50          60
3951       33    191   1694.368      -1         53          50
3952       33    192   2674.219      -1        122         110
3953       33    193   2228.699       1         67          80
3954       33    194   2848.448       1         80          67
3955       33    195   4027.628      -1         70          80
3956       33    196   2835.649       1        110         122
3957       33    197   8278.587      -1        110         115
3958       33    198   3903.836       1        110         112
3959       33    199   2579.740      -1        110         103

[3960 rows x 6 columns]

In [16]:
GLAM_output = pd.concat([new_expData_dataframe, IAFixDataFrame], axis = 1)
GLAM_output = GLAM_output.replace(-1, 0)
GLAM_output = GLAM_output.rename(index=str, columns={"parcode": "subject", "item_left": "item_value_0", "item_right": "item_value_1"})

In [17]:
## Remove participant 31 (because we lost a trial in the LESS frame)

In [18]:
GLAM_output = GLAM_output[GLAM_output.subject != 31]

In [19]:
GLAM_output.to_csv("Output/GlamDataPF2019_More_NoBin_33.csv",index = True)

-------------------------------------------------------------------------------------------

# LESS Condition Data

In [20]:
#for not binned data
data_fix = pd.read_csv('/Users/pradyumna/Documents/GiTs/PF2019/Output/fixations_collapsed_PF2019_Less_33.csv') 
data_expData = pd.read_csv('/Users/pradyumna/Documents/GiTs/PF2019/Output/expdata_PF2019_Less_33.csv') 

data_expData = data_expData.apply(pd.to_numeric, errors='ignore')
data_fix = data_fix.apply(pd.to_numeric, errors='ignore')

## Replace numerations

In [21]:
partNums = pd.unique(data_fix["parcode"])

new_fix_dataframe = data_fix.iloc[0:0]
new_expData_dataframe = data_expData.iloc[0:0]

for i in partNums:
    old_index_trial = []
    new_index_trial = []
    participant_trials = []
    
    participant_trials = data_expData.loc[data_expData['parcode'] == i]
    part_fix_trials = data_fix.loc[data_fix['parcode'] == i]
    
    old_index_trial = participant_trials['trial'].values
    new_index_trial = range(len(old_index_trial))
    
    for j in new_index_trial:
            #insert new column with new trial numeration : case trialData
            trialCol2Replace = participant_trials['trial'].replace(old_index_trial[j], new_index_trial[j])
            participant_trials = participant_trials.drop(['trial'], axis=1)
            participant_trials.insert(1,'trial',trialCol2Replace)
            
            #insert new column with new trial numeration : case Fixations
            fixCol2Replace = part_fix_trials['trial'].replace(old_index_trial[j], new_index_trial[j]).values
            part_fix_trials = part_fix_trials.drop(['trial'], axis=1)
            part_fix_trials.insert(1,'trial',fixCol2Replace)
            
            #print (participant_trials)
            time_trials = part_fix_trials['fix_time'].values
            
            ix = np.in1d(time_trials, 0)
            delete_fix_idx = np.where(ix)
            part_fix_trials = part_fix_trials.drop(part_fix_trials.index[delete_fix_idx])
            
    new_fix_dataframe = pd.concat([new_fix_dataframe, part_fix_trials],axis = 0)
    new_expData_dataframe = pd.concat([new_expData_dataframe, participant_trials], axis = 0)

## Format appropiate for GLAM toolbox for fixations
Agregate fixations for each IA (similar to dwelling time)

In [22]:
new_fix_dataframe

       parcode  trial  fix_item  fix_time
0            1     40         0   232.000
1            1     40         1  1008.000
2            1     40         2   956.000
3            1     40         1  1030.000
4            1     40         2   642.000
5            1     40         1   393.735
6            1     41         0   511.000
7            1     41         1   706.000
8            1     41         2   640.000
9            1     41         1   790.000
10           1     41         2   912.258
11           1     42         0   434.000
12           1     42         1  1030.000
13           1     42         2   764.000
14           1     42         1   384.000
15           1     42         0   440.000
16           1     42         2   702.464
17           1     43         0   226.000
18           1     43         1  1072.000
19           1     43         2   796.000
20           1     43         1   337.751
21           1     44         0     3.000
22           1     44         1  1232.000
23           1     44         2   654.000
24           1     44         1   310.342
25           1     45         0   198.000
26           1     45         1  1028.000
27           1     45         2  1122.000
28           1     45         1   921.922
29           1     46         0   235.000
...        ...    ...       ...       ...
23482       33    275         1   294.000
23483       33    275         0   228.000
23484       33    275         1   910.714
23486       33    276         1   425.000
23487       33    276         2  1312.000
23488       33    276         1   894.000
23489       33    276         2  1216.000
23490       33    276         1  1138.000
23491       33    276         2   818.000
23492       33    276         1   327.148
23494       33    277         1   409.000
23495       33    277         2  1012.000
23496       33    277         1  1252.000
23497       33    277         2  1162.000
23498       33    277         1  2004.000
23499       33    277         2  1450.000
23500       33    277         1   950.000
23501       33    277         2   395.543
23502       33    278         0    37.000
23503       33    278         1   424.000
23504       33    278         2  1036.000
23505       33    278         1  1088.000
23506       33    278         2   633.693
23507       33    279         0    41.000
23508       33    279         1   590.000
23509       33    279         2   906.000
23510       33    279         1  2376.000
23511       33    279         2  1218.000
23512       33    279         1   790.000
23513       33    279         2   619.174

[22939 rows x 4 columns]

In [23]:
partNums = pd.unique(new_fix_dataframe["parcode"])
partNums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [24]:
## Test for missing trials
for i in partNums:
    PartIAFixMatrix= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == i )]
    print(str(i) +" : " + str(len(PartIAFixMatrix.trial.unique())))

1 : 120
2 : 120
3 : 120
4 : 120
5 : 120
6 : 120
7 : 120
8 : 120
9 : 120
10 : 120
11 : 120
12 : 120
13 : 120
14 : 120
15 : 120
16 : 120
17 : 120
18 : 120
19 : 120
20 : 120
21 : 120
22 : 120
23 : 120
24 : 120
25 : 120
26 : 120
27 : 120
28 : 120
29 : 120
30 : 120
31 : 119
32 : 120
33 : 120

In [25]:
#PartIAFixMatrix= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == 31 )]
#PartIAFixMatrix.trial.unique() # Missing part 31 (P58) trial 58
#PartIAFixMatrix1= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == 31 ) & (new_fix_dataframe['trial'] == 58 )]
#PartIAFixMatrix1

## Fix numeration for fixation trials (NOT USED)

In [26]:
#for i in partNums:
#    for j in range(0,120):#

#    partFixations = new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == 31 ) & (new_fix_dataframe['trial'] == 58 )]
#    partTrials = part_fixations.trial.unique()

## SINCE participant 31, trial 58 is lost we wil remove that participant

In [27]:
new_fix_dataframe = new_fix_dataframe[new_fix_dataframe.parcode != 31]
new_expData_dataframe = new_expData_dataframe[new_expData_dataframe.parcode != 31]


new_fix_dataframe = new_fix_dataframe.reset_index(drop=True)
new_expData_dataframe = new_expData_dataframe.reset_index(drop=True)

In [28]:
new_fix_dataframe.parcode.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33])

In [29]:
IAFixMatrix = []

for i in partNums:
    PartIAFixMatrix= new_fix_dataframe.loc[(new_fix_dataframe['parcode'] == i )]
    trialNums = pd.unique(PartIAFixMatrix["trial"])
    for j in trialNums:
        PartTrialIAFixMatrix= PartIAFixMatrix.loc[(PartIAFixMatrix['trial'] == j )]
        
        #if len(PartTrialIAFixMatrix)<0:
            #print ('ero')
        #if len(PartTrialIAFixMatrix)<50:
           # print ('udo')
        
        
        # considering that IA 1 is left and IA 2 is right ( IAs 3 and 0 are not fixated in the item)
        # Sum left item
        LGazeTime = PartTrialIAFixMatrix.loc[PartTrialIAFixMatrix['fix_item'] == 1, 'fix_time'].sum() 
        # Sum right item
        RGazeTime = PartTrialIAFixMatrix.loc[PartTrialIAFixMatrix['fix_item'] == 2, 'fix_time'].sum()  
        LGaze = LGazeTime/(LGazeTime + RGazeTime)
        RGaze = RGazeTime/(LGazeTime + RGazeTime)
        
        RT = PartTrialIAFixMatrix.fix_time.sum()
        
        #IAFixMatrix.append([i,j,LGaze, RGaze]) 
        IAFixMatrix.append([LGaze, RGaze,RT])

In [30]:
#IAFixDataFrame = pd.DataFrame(IAFixMatrix,columns=['participants','trials','gaze_0','gaze_1'])
IAFixDataFrame = pd.DataFrame(IAFixMatrix,columns=['gaze_0','gaze_1','react_time'])

In [31]:
IAFixDataFrame

        gaze_0    gaze_1
0     0.603448  0.396552
1     0.490772  0.509228
2     0.490893  0.509107
3     0.639125  0.360875
4     0.702232  0.297768
5     0.634756  0.365244
6     0.602831  0.397169
7     0.600783  0.399217
8     0.475195  0.524805
9     0.436619  0.563381
10    0.638397  0.361603
11    0.642003  0.357997
12    0.605235  0.394765
13    0.586722  0.413278
14    0.479771  0.520229
15    0.579058  0.420942
16    0.629489  0.370511
17    0.726102  0.273898
18    0.694959  0.305041
19    0.618070  0.381930
20    0.636436  0.363564
21    0.736291  0.263709
22    0.642971  0.357029
23    0.605632  0.394368
24    0.565495  0.434505
25    0.640865  0.359135
26    0.468667  0.531333
27    0.651876  0.348124
28    0.519646  0.480354
29    0.539313  0.460687
...        ...       ...
3810  0.499230  0.500770
3811  0.603179  0.396821
3812  0.500618  0.499382
3813  0.490053  0.509947
3814  0.469571  0.530429
3815  0.601702  0.398298
3816  0.466509  0.533491
3817  0.555883  0.444117
3818  0.465549  0.534451
3819  0.444436  0.555564
3820  0.572452  0.427548
3821  0.629613  0.370387
3822  0.421237  0.578763
3823  0.432026  0.567974
3824  0.599172  0.400828
3825  0.558825  0.441175
3826  0.426795  0.573205
3827  0.466281  0.533719
3828  0.406985  0.593015
3829  0.485623  0.514377
3830  0.500810  0.499190
3831  0.606535  0.393465
3832  0.500242  0.499758
3833  0.488910  0.511090
3834  0.494589  0.505411
3835  0.544452  0.455548
3836  0.454173  0.545827
3837  0.534481  0.465519
3838  0.475219  0.524781
3839  0.577920  0.422080

[3840 rows x 2 columns]

In [32]:
#IAFixDataFrame.to_csv("Output/tests_IA.csv",index = True)

In [33]:
new_expData_dataframe

      parcode  trial        rt  choice  item_left  item_right
0           1      0  4261.735      -1        110         131
1           1      1  3559.258       1         47          50
2           1      2  3754.464       1         50          44
3           1      3  2431.751      -1         57          50
4           1      4  2199.342      -1         42          50
5           1      5  3269.922      -1        108         110
6           1      6  6606.698      -1         78          80
7           1      7  3642.146       1        110          92
8           1      8  5213.480       1         50          48
9           1      9  5511.334       1        110         101
10          1     10  2007.957      -1         46          50
11          1     11  3124.521       1         80          83
12          1     12  1978.076      -1         50          56
13          1     13  2508.548       1         50          47
14          1     14  3907.246       1        110         124
15          1     15  3482.062       1         91          80
16          1     16  1823.377      -1         64          80
17          1     17  5111.944      -1         83          80
18          1     18  4920.474      -1        101         110
19          1     19  1869.935      -1         56          50
20          1     20  1705.811      -1         50          42
21          1     21  3083.540      -1        110         117
22          1     22  2474.714      -1         77          80
23          1     23  2272.349      -1         80          91
24          1     24  3790.480      -1         44          50
25          1     25  2046.062      -1         50          57
26          1     26  3822.251       1         50          46
27          1     27  3347.540      -1        110         108
28          1     28  2252.245       1        133         110
29          1     29  2083.424       1        131         110
...       ...    ...       ...     ...        ...         ...
3810       33     90  2154.276       1         80          70
3811       33     91  1635.658      -1         80          93
3812       33     92  3600.589       1         82          80
3813       33     93  1985.539       1         50          41
3814       33     94  3099.150      -1         96         110
3815       33     95  2016.568      -1         80          85
3816       33     96  4201.412       1         60          50
3817       33     97  7393.335      -1         41          50
3818       33     98  2128.968       1        110          96
3819       33     99  3018.356      -1         72          80
3820       33    100  2593.981      -1         49          50
3821       33    101  5548.946      -1         43          50
3822       33    102  3422.548       1         51          50
3823       33    103  2089.469       1        112         110
3824       33    104  3026.628      -1         40          50
3825       33    105  1934.204      -1         50          51
3826       33    106  4261.328       1         85          80
3827       33    107  3629.222      -1         50          49
3828       33    108  2831.685       1         50          43
3829       33    109  4352.493      -1         80          82
3830       33    110  1522.433      -1         50          60
3831       33    111  2025.634      -1         53          50
3832       33    112  2271.982       1        122         110
3833       33    113  3836.855      -1         67          80
3834       33    114  3589.465       1         80          67
3835       33    115  3708.714      -1         70          80
3836       33    116  6127.148      -1        110         122
3837       33    117  8632.543       1        110         115
3838       33    118  3218.693       1        110         112
3839       33    119  6540.174       1        110         103

[3840 rows x 6 columns]

In [34]:
GLAM_output = pd.concat([new_expData_dataframe, IAFixDataFrame], axis = 1)
GLAM_output = GLAM_output.replace(-1, 0)
GLAM_output = GLAM_output.rename(index=str, columns={"parcode": "subject", "item_left": "item_value_0", "item_right": "item_value_1"})

In [35]:
GLAM_output.to_csv("Output/GlamDataPF2019_Less_NoBin_33.csv",index = True)

In [36]:
z_matrix_values = []
for i in (expdata_frame['parcode'].unique()):
    Choicedata_ddm = expdata_frame.loc[expdata_frame['parcode'] == i]
    
    pX_LV =  pd.to_numeric(Choicedata_ddm["item_left"]) 
    pX_RV =   pd.to_numeric(Choicedata_ddm["item_right"])
    meanLV = np.mean(pX_LV)
    stdLV =  np.std(pX_LV)
    meanRV = np.mean(pX_RV)
    stdRV =  np.std(pX_RV)
    p_zLV = (pX_LV - meanLV)/stdLV
    p_zRV = (pX_RV - meanRV)/stdRV
     
    # We generate bins using the z-scored values.
    # We consider 6 levels
    # 1 . -inf < x <  -2*std
    # 2 . -2*std <= x <  -std
    # 3 . -std <= x <  0
    # 4 . 0 <= x <  std
    # 5 . std <= x <  2*std
    # 6 . 2*std <= x <  inf
    
    binLV =  -1
    binRV =  -1
    p_binLV = []
    p_binRV = []
    
    
    # Avoid the problem of indexing
    p_zLV = p_zLV.reset_index()
    p_zRV = p_zRV.reset_index()
    
    p_zLV = p_zLV.drop(['index'], 1)
    p_zRV = p_zRV.drop(['index'], 1)

    p_zLV = p_zLV["item_left"]
    p_zRV = p_zRV["item_right"]

    # 6 bins for the value
    for  j in range(len(p_zLV)):  
        # bin the value of the left item 
        if p_zLV[j] < (-2*stdLV):
            binLV = 0
        elif -2*stdLV <= p_zLV[j] and p_zLV[j]< -stdLV:
            binLV = 1
        elif -stdLV <= p_zLV[j] and p_zLV[j]< 0:
            binLV = 2
        elif 0 <= p_zLV[j] and p_zLV[j]< stdLV:
            binLV = 3
        elif stdLV <= p_zLV[j] and p_zLV[j]< 2*stdLV:
            binLV = 4
        elif 2*stdLV <=p_zLV[j]:
            binLV = 5
        
        # bin the value of the left item 
        if p_zRV[j] < -2*stdRV:
            binRV = 0
        elif -2*stdRV <= p_zRV[j] and p_zRV[j]< -stdRV:
            binRV = 1
        elif -stdRV <= p_zRV[j] and p_zRV[j]< 0:
            binRV = 2
        elif 0 <= p_zRV[j] and p_zRV[j]< stdRV:
            binRV = 3
        elif stdRV <= p_zRV[j] and p_zRV[j]< 2*stdRV:
            binRV = 4
        elif 2*stdRV < p_zRV[j]:
            binRV = 5
        
        p_binLV.append(binLV)
        p_binRV.append(binRV)
    
    z_matrix_aux= np.column_stack((p_zLV,p_zRV,p_binLV,p_binRV))
    
    for  j in range(len(z_matrix_aux)):    
        z_matrix_values.append(z_matrix_aux[j])

NameError: name 'expdata_frame' is not defined